# Site settings
title: 4th Connecticut Regiment, Captain Fitch's Company
email: tsmacdonald@gmail.com
url: http://4thct.com
description: "A modern recreation of the 4th CT Regt, Fitch's Company, in June 1778"
skills: ""
meta_author: Macdonald Tim

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5D2F25
  primary-rgb: "93,47,37"
  secondary: D90633
  secondary-dark: D90633

# Footer settings
footer:
  copyright: Timothy Macdonald
  location: Location
  social: Find us on Facebook
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/4thct

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
